public final class kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed extends java.lang.Exception
{
    public static final kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed INSTANCE;

    static void <clinit>()
    {
        kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed $r0;

        $r0 = new kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed;

        specialinvoke $r0.<kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed: void <init>()>();

        <kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed: kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed INSTANCE> = $r0;

        return;
    }

    private void <init>()
    {
        kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed r0;

        r0 := @this: kotlinx.coroutines.internal.ExceptionSuccessfullyProcessed;

        specialinvoke r0.<java.lang.Exception: void <init>()>();

        return;
    }
}
